### PR TITLE
GC concurrent issue potential fix

### PR DESCRIPTION
**Pull request by tosbaha**
Fixes from @pratikpatel39 according to this [issue](https://github.com/facebook/react-native/issues/25494#issuecomment-560544769)

### CODE REVIEW

**Comment by Kudo** [comment]
Thank you @tosbaha, do you mind to put the original WebKit patch directly? It would be better to appreciate original author's work.
It seems your branch has the permissions for me to edit directly. If you don't mind, I could edit on your branch and then merge your PR.

**Comment by tosbaha** [comment]
Hi @Kudo , I got the combined patches from the [linked](https://github.com/facebook/react-native/issues/25494#issuecomment-560544769) thread. Which actually links to https://trac.webkit.org/changeset/251307/webkit Since the patches were pointing to the different directories, @pratikpatel39  fixed the patches and unified the patch. I don't know how can I put the original WebKit patch directly. I checked the patches in this repository there were no authors etc. Please edit the PR as you please.

**Comment by Kudo** [comment]
Sorry to make you confuse. I was talking about including the CHANGELOG.
Will modify your PR and merge directly. Thank you very much.

**Comment by Kudo** [comment]
I've modified your PR and merged back to jsc_2_26_1 branch.
Will follow up to merge this patch to my develop branch and hopefully to publish new version soon.
Thank you.

**Pull request merged**
